### ISSUE TITLE
Deprecate this library

### ISSUE THREAD

**Issue by erip** [puiterwijk/flask-oidc#60] opened 2018-08-01 17:08 UTC
Google recently deprecate `oauth2client` in favor of [google-auth](https://google-auth.readthedocs.io/en/latest/). Since this library leans so heavily on the oauth2client, it might be good to deprecate this library or, at the very least, warn of the deprecation of `oauth2client`.

**Comment by MartinThoma** [comment] 2019-07-29 13:59
This is a duplicate of #33 and #85. I think this one should be closed.

**Closed** 2020-02-08 23:02 UTC
